### ISSUE TITLE
Crashes World

### ISSUE THREAD

**Issue by Graywaren** [gbuimc/NeatForRift#2]
Installiing with 1.13.2 and rift for that using MultiMC. I can launch a new world and it will almost load but then it will crash. Seems possibly related to the keybind issue mentioned on curseforge comments. Here's the crash log:

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 1/29/19 3:17 PM
Description: Unexpected error

java.lang.RuntimeException: Failed to create listener instance
	at org.dimdev.riftloader.RiftLoader.loadListeners(RiftLoader.java:266)
	at org.dimdev.riftloader.RiftLoader.getListeners(RiftLoader.java:239)
	at cft.handler$onProcessKeyBinds$zbk000(SourceFile:2387)
	at cft.aw(SourceFile)
	at cft.m(SourceFile:1251)
	at cft.c(SourceFile:821)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.dimdev.riftloader.RiftLoader.newInstance(RiftLoader.java:283)
	at org.dimdev.riftloader.RiftLoader.loadListeners(RiftLoader.java:263)
	... 21 more
Caused by: java.lang.InstantiationError: cfe
	at vazkii.neat.ToggleKeybind.<init>(ToggleKeybind.java:16)
	... 27 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.dimdev.riftloader.RiftLoader.loadListeners(RiftLoader.java:266)
	at org.dimdev.riftloader.RiftLoader.getListeners(RiftLoader.java:239)
	at cft.handler$onProcessKeyBinds$zbk000(SourceFile:2387)
	at cft.aw(SourceFile)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [ctj['Graywaren'/288, l='MpServer', x=-230.50, y=67.00, z=226.50]]
	Chunk stats: MultiplayerChunkCache: 532, 532
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-224,65,224), Chunk: (at 0,4,0 in -14,14; contains blocks -224,0,224 to -209,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 43 game time, 43 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 78 total; [ajt['Cow'/140, l='MpServer', x=-164.00, y=65.00, z=238.00], ajt['Cow'/141, l='MpServer', x=-162.99, y=66.00, z=238.04], ajt['Cow'/142, l='MpServer', x=-164.00, y=66.00, z=239.00], ajt['Cow'/143, l='MpServer', x=-162.97, y=66.00, z=238.01], akf['Sheep'/144, l='MpServer', x=-161.00, y=67.00, z=234.00], akf['Sheep'/145, l='MpServer', x=-164.00, y=65.00, z=237.00], akf['Sheep'/146, l='MpServer', x=-164.00, y=65.00, z=236.00], ajr['Chicken'/147, l='MpServer', x=-167.13, y=64.00, z=269.87], ajr['Chicken'/148, l='MpServer', x=-170.00, y=64.00, z=271.00], ajt['Cow'/21, l='MpServer', x=-309.00, y=64.00, z=233.00], ajr['Chicken'/149, l='MpServer', x=-167.37, y=64.00, z=271.14], ajt['Cow'/22, l='MpServer', x=-310.00, y=64.00, z=233.00], ajr['Chicken'/150, l='MpServer', x=-168.00, y=64.00, z=270.00], ajt['Cow'/24, l='MpServer', x=-310.00, y=64.00, z=232.00], amm['Rail'/280, l='MpServer', x=-232.10, y=39.04, z=222.13], amm['Rail'/281, l='MpServer', x=-223.73, y=39.05, z=222.13], amm['Rail'/282, l='MpServer', x=-251.13, y=39.00, z=225.25], amm['Rail'/284, l='MpServer', x=-224.88, y=39.00, z=223.39], amm['Rail'/285, l='MpServer', x=-231.25, y=39.00, z=223.65], amm['Rail'/286, l='MpServer', x=-222.81, y=39.00, z=222.69], ajt['Cow'/31, l='MpServer', x=-306.00, y=64.00, z=214.00], amm['Rail'/287, l='MpServer', x=-231.98, y=39.74, z=223.34], ajt['Cow'/32, l='MpServer', x=-307.02, y=64.00, z=212.04], ajt['Cow'/33, l='MpServer', x=-308.00, y=64.00, z=211.00], amt['Creeper'/289, l='MpServer', x=-243.50, y=23.00, z=272.50], apl['Minecart with Chest'/35, l='MpServer', x=-273.50, y=39.06, z=271.50], ajl['Bat'/298, l='MpServer', x=-184.50, y=21.00, z=224.50], ajl['Bat'/299, l='MpServer', x=-182.50, y=21.00, z=219.50], ajl['Bat'/300, l='MpServer', x=-185.50, y=21.00, z=222.50], ajl['Bat'/301, l='MpServer', x=-184.50, y=21.00, z=223.50], ajl['Bat'/302, l='MpServer', x=-212.50, y=49.00, z=171.50], ajl['Bat'/304, l='MpServer', x=-210.50, y=49.00, z=171.50], ajl['Bat'/305, l='MpServer', x=-209.50, y=49.00, z=171.50], ajl['Bat'/306, l='MpServer', x=-213.50, y=49.00, z=174.50], ann['Skeleton'/435, l='MpServer', x=-207.50, y=25.00, z=271.50], ajl['Bat'/310, l='MpServer', x=-206.50, y=21.00, z=297.50], ajl['Bat'/312, l='MpServer', x=-211.50, y=21.00, z=298.50], apl['Minecart with Chest'/59, l='MpServer', x=-242.50, y=40.06, z=210.50], apl['Minecart with Chest'/60, l='MpServer', x=-251.49, y=39.00, z=223.61], apl['Minecart with Chest'/61, l='MpServer', x=-241.50, y=38.06, z=264.50], akm['Wolf'/62, l='MpServer', x=-243.00, y=71.00, z=281.00], akm['Wolf'/63, l='MpServer', x=-249.00, y=73.00, z=285.00], akm['Wolf'/64, l='MpServer', x=-241.00, y=70.00, z=285.00], akf['Sheep'/197, l='MpServer', x=-153.00, y=63.00, z=271.00], akf['Sheep'/198, l='MpServer', x=-156.00, y=64.00, z=271.00], ajl['Bat'/454, l='MpServer', x=-255.50, y=39.00, z=227.50], akf['Sheep'/200, l='MpServer', x=-156.00, y=64.00, z=270.00], ajr['Chicken'/201, l='MpServer', x=-153.00, y=67.00, z=260.00], ake['Salmon'/329, l='MpServer', x=-296.50, y=58.00, z=171.50], ajl['Bat'/457, l='MpServer', x=-259.50, y=39.00, z=228.50], ajr['Chicken'/202, l='MpServer', x=-153.00, y=67.00, z=260.00], ake['Salmon'/330, l='MpServer', x=-297.50, y=58.00, z=171.50], ake['Salmon'/331, l='MpServer', x=-299.50, y=58.00, z=170.50], ajl['Bat'/459, l='MpServer', x=-260.50, y=39.00, z=227.50], akf['Sheep'/76, l='MpServer', x=-233.41, y=68.00, z=227.46], akf['Sheep'/77, l='MpServer', x=-236.00, y=70.00, z=230.00], ake['Salmon'/333, l='MpServer', x=-183.50, y=61.00, z=236.50], ajl['Bat'/461, l='MpServer', x=-256.50, y=39.00, z=227.50], akf['Sheep'/78, l='MpServer', x=-239.00, y=70.00, z=225.00], ake['Salmon'/334, l='MpServer', x=-183.50, y=61.00, z=233.50], akf['Sheep'/79, l='MpServer', x=-235.00, y=70.00, z=230.00], ake['Salmon'/335, l='MpServer', x=-183.50, y=61.00, z=231.50], ctj['Graywaren'/288, l='MpServer', x=-230.50, y=67.00, z=226.50], ake['Salmon'/337, l='MpServer', x=-184.50, y=61.00, z=236.50], aki['Squid'/338, l='MpServer', x=-180.50, y=61.00, z=235.50], ajs['Cod'/339, l='MpServer', x=-303.50, y=42.00, z=169.50], ajs['Cod'/340, l='MpServer', x=-302.50, y=42.00, z=169.50], ajs['Cod'/341, l='MpServer', x=-302.50, y=42.00, z=166.50], akk['Turtle'/94, l='MpServer', x=-234.50, y=64.00, z=171.40], akk['Turtle'/95, l='MpServer', x=-234.02, y=64.00, z=169.64], akk['Turtle'/96, l='MpServer', x=-232.00, y=61.00, z=168.60], akf['Sheep'/97, l='MpServer', x=-239.10, y=71.00, z=259.00], akf['Sheep'/98, l='MpServer', x=-236.00, y=71.00, z=259.00], akf['Sheep'/99, l='MpServer', x=-238.00, y=71.00, z=259.00], akf['Sheep'/100, l='MpServer', x=-238.96, y=71.00, z=262.04], ajl['Bat'/493, l='MpServer', x=-266.50, y=39.00, z=241.50], amm['Rail'/495, l='MpServer', x=-233.51, y=39.60, z=223.49], amm['Rail'/496, l='MpServer', x=-221.26, y=39.37, z=223.25]]
	Retry entities: 0 total; []
	Server brand: rift
	Server type: Integrated singleplayer server
Stacktrace:
	at crg.a(SourceFile:418)
	at cft.b(SourceFile:1815)
	at cft.a(SourceFile:408)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1841097248 bytes (1755 MB) / 2406481920 bytes (2295 MB) up to 5607784448 bytes (5348 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx6016m
	Launched Version: MultiMC5
	LWJGL: 3.1.6 build 14
	OpenGL: Intel(R) HD Graphics 630 GL version 4.5.0 - Build 25.20.100.6373, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'rift'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

**Comment by gbl** [comment]
This is a 1.13 mod that won't work on 1.13.2. Seems like there's been a pull request around for a while that updates to 1.13.2, but which the author didn't include yet.
